#!/bin/sh

# Create webroot
mkdir /var/clearos/wordpress/webroot

# Active Fleshare
/usr/sbin/flexshare -n webapp-wordpress -a activate >/dev/null 2>&1

# Initialize database
/usr/sbin/systemdb wordpress
